sudo: required
services:
  - docker

# before_install:
#   - docker build -t destinyforge/hsse-admin-client-test -f ./admin/Dockerfile ./admin

script:
  - docker ps -a

after_success:
  - echo "Success - ..."
  - docker build -t destinyforge/hsse-client ./client --build-arg REACT_APP_BACKEND_SERVER=$REACT_APP_BACKEND_SERVER
  - docker build -t destinyforge/hsse-admin-client ./admin --build-arg REACT_APP_BACKEND_SERVER=$REACT_APP_BACKEND_SERVER
  - docker build -t destinyforge/hsse-nginx ./nginx
  - docker build -t destinyforge/hsse-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push destinyforge/hsse-client
  - docker push destinyforge/hsse-admin-client
  - docker push destinyforge/hsse-nginx
  - docker push destinyforge/hsse-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: hsse-project-staging
  env: HsseProjectStaging-env
  bucket_name: elasticbeanstalk-us-east-1-566498504664
  bucket_path: hsse-project-staging
  on:
    branch: master
  access_key_id: $AWS_ELB_ACCESS_KEY
  secret_access_key: $AWS_ELB_SECRET_KEY
