version: '3.6'
services:
  mongo:
    image: mongo
    ports:
      - '37017:27017'

  hsse-admin-client:
    build: ./client
    ports:
      - '4000:4000'

  hsse-admin-client:
    build: ./admin
    ports:
      - '5000:5000'

  hsse-server:
    build: ./server
    ports:
      - '5001:3000'
    environment:
      - APP_BASE_URL=
      - APP_VERSION=
      - API_SWAGGER=
      - FRONTEND_URL=localhost:4000
      - DATABASE_URL=mongodb://mongo:27017
      - DATABASE_URL_TEST=mongodb://mongo:27017
      - DATABASE_URL_STAGING=
      - DATABASE_URL_PRODUCTION=
      - PORT=4000
      - TIMEZONE=
      - SECRET=akfjlaksdjlasfjasdfljiasdfasfksldf

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - hsse-server
      - hsse-client
      - hsse-admin-client
