const t = require("tcomb");
const Filter = require("./filter");
const { compose } = require("ramda");
const { cleanData, cleanMongoId } = require("../helper");

const HSEFilter = Filter.extend(
  {
    documentType: t.String,

    // Health System Topics
    government: t.Boolean,
    governmentPolicy: t.Boolean,
    governmentPolicyCentralization: t.Boolean,
    governmentPolicyAccountability: t.Boolean,
    governmentPolicyStewardship: t.Boolean,
    governmentPolicyDecisionMaking: t.Boolean,
    governmentPolicyCorruptionProtections: t.Boolean,

    organization: t.Boolean,
    organizationOwnership: t.Boolean,
    organizationManagement: t.Boolean,
    organizationAccreditation: t.Boolean,
    organizationNetworks: t.Boolean,

    commercial: t.Boolean,
    commercialLicense: t.Boolean,
    commercialPatentsAndProfits: t.Boolean,
    commercialPricingAndPurchasing: t.Boolean,
    commercialMarketing: t.Boolean,
    commercialSalesAndDispensing: t.Boolean,
    commercialLiability: t.Boolean,

    professional: t.Boolean,
    professionalTrainingAndLicense: t.Boolean,
    professionalScopeOfPractice: t.Boolean,
    professionalContinuingCompetance: t.Boolean,
    professionalQualityAndSafety: t.Boolean,
    professionalLiability: t.Boolean,
    professionalStrikeJobAction: t.Boolean,

    consumer: t.Boolean,
    consumerPolicyDecisions: t.Boolean,
    consumerSystemMonitoring: t.Boolean,
    consumerServiceDelivery: t.Boolean,
    consumerComplaintsManagement: t.Boolean,
    consumerStakeholder: t.Boolean,

    financial: t.Boolean,
    financialSystems: t.Boolean,
    financialTaxation: t.Boolean,
    financialSocialHealthInsurance: t.Boolean,
    financialCommunityBasedHealthInsurance: t.Boolean,
    financialCommunityLoanFunds: t.Boolean,
    financialPrivateInsurance: t.Boolean,
    financialHealthSavingsAccountsIndividuallyFinanced: t.Boolean,
    financialUserFees: t.Boolean,
    financialDonorContributions: t.Boolean,
    financialFundraising: t.Boolean,

    fundingOrganization: t.Boolean,
    fundingOrganizationServiceFees: t.Boolean,
    fundingOrganizationCapitation: t.Boolean,
    fundingOrganizationGlobalBudget: t.Boolean,
    fundingOrganizationProspectivePayment: t.Boolean,
    fundingOrganizationIndicativeBudgets: t.Boolean,
    fundingOrganizationPaymentsPenalties: t.Boolean,

    remuneratingProvider: t.Boolean,
    remuneratingProviderServiceFees: t.Boolean,
    remuneratingProviderCapitation: t.Boolean,
    remuneratingProviderSalary: t.Boolean,
    remuneratingProviderProspectivePayment: t.Boolean,
    remuneratingProviderFundholding: t.Boolean,
    remuneratingProviderIndicativeBudgets: t.Boolean,
    remuneratingProviderPaymentPenalties: t.Boolean,

    purchasing: t.Boolean,
    purchasingScope: t.Boolean,
    purchasingCoveredReimbursedOrganizations: t.Boolean,
    purchasingRestrictions: t.Boolean,
    purchasingCaps: t.Boolean,
    purchasingApprovalRequirements: t.Boolean,
    purchasingSubstitutes: t.Boolean,

    incentivizingConsumer: t.Boolean,
    incentivizingConsumerPremium: t.Boolean,
    incentivizingConsumerCostSharing: t.Boolean,
    incentivizingConsumerSavingsThirdPartyContributions: t.Boolean,
    incentivizingConsumerSavingsTargetedPaymentsPenalties: t.Boolean,

    deliveryArrangement: t.Boolean,
    deliveryArrangementCare: t.Boolean,
    deliveryArrangementCareAvailability: t.Boolean,
    deliveryArrangementCareTimelyAcess: t.Boolean,
    deliveryArrangementCareCulturallyAppropriate: t.Boolean,
    deliveryArrangementCareCaseManagement: t.Boolean,
    deliveryArrangementCareDiseaseManagement: t.Boolean,
    deliveryArrangementCareGroup: t.Boolean,

    careProvider: t.Boolean,
    careProviderSystemDemandSupply: t.Boolean,
    careProviderSystemRecruitmentRetention: t.Boolean,
    careProviderSystemPerformanceManagement: t.Boolean,
    careProviderWorkplaceConditionsProviderSatisfaction: t.Boolean,
    careProviderWorkplaceConditionsHealthSafety: t.Boolean,
    careProviderSkillMixRolePerformance: t.Boolean,
    careProviderSkillMixRoleExpansionOrExtension: t.Boolean,
    careProviderSkillMixTaskShiftingSubstitution: t.Boolean,
    careProviderSkillMixMultidisciplinaryTeams: t.Boolean,
    careProviderSkillMixVolunteersOrInformalFamilyCaregivers: t.Boolean,
    careProviderSkillMixCommunicationDistantHealthProfessionals: t.Boolean,
    careProviderStaffTraining: t.Boolean,
    careProviderStaffSupport: t.Boolean,
    careProviderStaffWorkloadWorkflowIntensity: t.Boolean,
    careProviderStaffContinuityOfCare: t.Boolean,
    careProviderStaffSelfSharedDecisionMaking: t.Boolean,
    careProviderSelfManagement: t.Boolean,

    careSource: t.Boolean,
    careSourceSiteOfServiceDelivery: t.Boolean,
    careSourcePhysicalstructureFacilitiesEquipment: t.Boolean,
    careSourceOrganizationalScale: t.Boolean,
    careSourceIntegrationOfServices: t.Boolean,
    careSourceContinuityOfCare: t.Boolean,
    careSourceOutreach: t.Boolean,

    careSupport: t.Boolean,
    careSupportHealthRecordSystems: t.Boolean,
    careSupportElectronicHealthRecord: t.Boolean,
    careSupportOtherICTThatSupportIndividuals: t.Boolean,
    careSupportICTThatSupportIndividualsWhoReceiveCare: t.Boolean,
    careSupportQualityMonitoringAndImprovementSystems: t.Boolean,
    careSupportSafetyMonitoringAndImprovementSystems: t.Boolean,

    implementationStrategies: t.Boolean,
    implementationConsumerTargetedStrategy: t.Boolean,
    implementationInformationOrEducationProvision: t.Boolean,
    implementationBehaviourChangeSupport: t.Boolean,
    implementationSkillsAndCompetenciesDevelopment: t.Boolean,
    implementationPersonalSupport: t.Boolean,
    implementationCommunicationAndDecisionMakingFacilitation: t.Boolean,
    implementationSystemParticipation: t.Boolean,

    providerStrategies: t.Boolean,
    providerStrategyEducationalMaterial: t.Boolean,
    providerStrategyEducationalMeeting: t.Boolean,
    providerStrategyEducationalOutreachVisit: t.Boolean,
    providerStrategyLocalOpinionLeader: t.Boolean,
    providerStrategyLocalConsensusProcess: t.Boolean,
    providerStrategyPeerReview: t.Boolean,
    providerStrategyAuditAndFeedback: t.Boolean,
    providerStrategyRemindersAndPrompts: t.Boolean,
    providerStrategyTailoredIntervention: t.Boolean,
    providerStrategyPatientMediatedIntervention: t.Boolean,
    providerStrategyMultiFacetedIntervention: t.Boolean,

    organizationStrategy: t.Boolean,

    // Province focus
    territoryFederalNational: t.Boolean,
    territoryAlberta: t.Boolean,
    territoryBritishColumbia: t.Boolean,
    territoryManitoba: t.Boolean,
    territoryNewBrunswick: t.Boolean,
    territoryNewFoundlandAndLabrador: t.Boolean,
    territoryNorthwestTerritories: t.Boolean,
    territoryNovaScotia: t.Boolean,
    territoryNunavut: t.Boolean,
    territoryOntario: t.Boolean,
    territoryPrinceEdwardIsland: t.Boolean,
    territoryQuebec: t.Boolean,
    territorySaskatchewan: t.Boolean,
    territoryYukon: t.Boolean,

    // New Canadian Areas
    canadianHomeAndCommunityCare: t.Boolean,
    canadianMentalHealthAndAddictionServices: t.Boolean,
    canadianIndigenousHealthFederal: t.Boolean,
    canadianAgingEmergent: t.Boolean,

    // Domains
    conditions: t.Boolean,
    conditionInfectiousDiseases: t.Boolean,
    conditionHIVAIDS: t.Boolean,
    conditionTuberculosis: t.Boolean,
    conditionMalaria: t.Boolean,
    conditionDiarrhoealDisease: t.Boolean,
    conditionLowerRespiratoryInfections: t.Boolean,

    conditionNonCommunicableDiseases: t.Boolean,
    conditionCancer: t.Boolean,
    conditionCardiovascularDisease: t.Boolean,
    conditionDiabetes: t.Boolean,
    conditionAlzheimerAndOtherDementias: t.Boolean,
    conditionsChronicObstructivePulmonaryDisease: t.Boolean,

    conditionOther: t.Boolean,
    conditionMaternalAndChildHealth: t.Boolean,
    conditionAccidents: t.Boolean,
    conditionMentalHealthAddictions: t.Boolean,

    conditionTechnologies: t.Boolean,
    conditionTechnologyDrugs: t.Boolean,
    conditionTechnologyDevices: t.Boolean,
    conditionTechnologyDiagnostics: t.Boolean,
    conditionTechnologySurgery: t.Boolean,

    // New Sectors
    conditionSectors: t.Boolean,
    conditionSectorPrimaryCare: t.Boolean,
    conditionSectorSpecialHospitalCare: t.Boolean,
    conditionSectorRehabilitationCare: t.Boolean,
    conditionSectorLongTermCare: t.Boolean,
    conditionSectorPublicHealth: t.Boolean,

    conditionProviders: t.Boolean,
    conditionProviderPhysician: t.Boolean,
    conditionProviderGeneralist: t.Boolean,
    conditionProviderSpecialist: t.Boolean,
    conditionProviderNurse: t.Boolean,
    conditionProviderPharmacist: t.Boolean,
    conditionProviderAlliedHealthProfessional: t.Boolean,
    conditionProviderLayCommunityCealthWorker: t.Boolean,
    conditionProviderInformalFamilyCaregivers: t.Boolean,

    // LMIC Focus
    lmicTargetOfDocument: t.Boolean,
    lmicAtLeastOneAuthor: t.Boolean,
    lmicAtLeastOneStudy: t.Boolean,

    // Theme
    themeOptimalAging: t.Boolean,
    themeHealthPromotionPrimaryPrevention: t.Boolean,

    // Population
    populationChildrenAndYouth: t.Boolean,
    populationIndigenousPeoples: t.Boolean,
    populationOldAdults: t.Boolean,

    // Information for evidence briefs
    evidenceFocusOfDocuments: t.String,
    evidenceKeyFindings: t.String,

    // Ontario priority areas
    ontarioPriorityCommunityBasedCare: t.Boolean,
    ontarioPriorityHealthSystemPerformanceAndSustainability: t.Boolean,
    ontarioPriorityHealthyLivingWithAFocusOnTobaccoControl: t.Boolean,
    ontarioPriorityMentalHealthAndAddictions: t.Boolean,
    ontarioPriorityNursingResearch: t.Boolean,
    ontarioPriorityPrimaryCareReform: t.Boolean,
    ontarioPriorityQualityImprovementAndSafety: t.Boolean,
    ontarioPrioritySeniorsCare: t.Boolean,
    ontarioPriorityVulnerableAndSpecialHealthNeedsPopulations: t.Boolean,
    ontarioPriorityWomensHealth: t.Boolean,

    healthSystemData: t.Boolean,
    healthSystemExpenditureReview: t.Boolean,
    healthSystemNationalAccount: t.maybe(t.Boolean),
    healthSystemProvincialAccount: t.maybe(t.Boolean),
    healthSystemResearchPriorities: t.Boolean,
    healthSystemSituationAnalysis: t.Boolean,
    healthSystemJurisdictionalReview: t.Boolean,
    healthSystemPerformanceReview: t.Boolean,
    healthSystemExternalEvaluation: t.Boolean,
    healthSystemLiteratureReview: t.Boolean,
    healthSystemFramework: t.Boolean,
    healthSystemToolkit: t.Boolean,
    healthSystemOptionsFraming: t.Boolean,
    healthSystemGuidance: t.Boolean,
    healthSystemCitizenPatientInput: t.Boolean,
    healthSystemStakeholderInput: t.Boolean,
    healthSystemStakeholderPositionPaper: t.Boolean,
    healthSystemPoliticalPartyPlatform: t.maybe(t.Boolean),
    healthSystemGovernmentDiscussionPaper: t.Boolean,
    healthSystemGovernmentPositionPaper: t.Boolean,
    healthSystemGovernmentStrategicPlan: t.Boolean,
    healthSystemGovernmentPolicy: t.Boolean,
    healthSystemGovernmentLegislation: t.Boolean,
    healthSystemIntergovernmentalCommunique: t.Boolean,
    healthSystemIntergovernmentalAccord: t.Boolean,
    healthSystemGovernmentThirdPartyAccord: t.Boolean
  },
  {
    defaultProps: {
      type: "hse",
      documentType:
        "NO. After reviewing the document types and eligibility criteria, this record is not eligible for inclusion in HSE.",

      government: false,
      governmentPolicy: false,
      governmentPolicyCentralization: false,
      governmentPolicyAccountability: false,
      governmentPolicyStewardship: false,
      governmentPolicyDecisionMaking: false,
      governmentPolicyCorruptionProtections: false,

      organization: false,
      organizationOwnership: false,
      organizationManagement: false,
      organizationAccreditation: false,
      organizationNetworks: false,

      commercial: false,
      commercialLicense: false,
      commercialPatentsAndProfits: false,
      commercialPricingAndPurchasing: false,
      commercialMarketing: false,
      commercialSalesAndDispensing: false,
      commercialLiability: false,

      professional: false,
      professionalTrainingAndLicense: false,
      professionalScopeOfPractice: false,
      professionalContinuingCompetance: false,
      professionalQualityAndSafety: false,
      professionalLiability: false,
      professionalStrikeJobAction: false,

      consumer: false,
      consumerPolicyDecisions: false,
      consumerSystemMonitoring: false,
      consumerServiceDelivery: false,
      consumerComplaintsManagement: false,
      consumerStakeholder: false,

      financial: false,
      financialSystems: false,
      financialTaxation: false,
      financialSocialHealthInsurance: false,
      financialCommunityBasedHealthInsurance: false,
      financialCommunityLoanFunds: false,
      financialPrivateInsurance: false,
      financialHealthSavingsAccountsIndividuallyFinanced: false,
      financialUserFees: false,
      financialDonorContributions: false,
      financialFundraising: false,

      fundingOrganization: false,
      fundingOrganizationServiceFees: false,
      fundingOrganizationCapitation: false,
      fundingOrganizationGlobalBudget: false,
      fundingOrganizationProspectivePayment: false,
      fundingOrganizationIndicativeBudgets: false,
      fundingOrganizationPaymentsPenalties: false,

      remuneratingProvider: false,
      remuneratingProviderServiceFees: false,
      remuneratingProviderCapitation: false,
      remuneratingProviderSalary: false,
      remuneratingProviderProspectivePayment: false,
      remuneratingProviderFundholding: false,
      remuneratingProviderIndicativeBudgets: false,
      remuneratingProviderPaymentPenalties: false,

      purchasing: false,
      purchasingScope: false,
      purchasingCoveredReimbursedOrganizations: false,
      purchasingRestrictions: false,
      purchasingCaps: false,
      purchasingApprovalRequirements: false,
      purchasingSubstitutes: false,

      incentivizingConsumer: false,
      incentivizingConsumerPremium: false,
      incentivizingConsumerCostSharing: false,
      incentivizingConsumerSavingsThirdPartyContributions: false,
      incentivizingConsumerSavingsTargetedPaymentsPenalties: false,

      deliveryArrangement: false,
      deliveryArrangementCare: false,
      deliveryArrangementCareAvailability: false,
      deliveryArrangementCareTimelyAcess: false,
      deliveryArrangementCareCulturallyAppropriate: false,
      deliveryArrangementCareCaseManagement: false,
      deliveryArrangementCareDiseaseManagement: false,
      deliveryArrangementCareGroup: false,

      careProvider: false,
      careProviderSystemDemandSupply: false,
      careProviderSystemRecruitmentRetention: false,
      careProviderSystemPerformanceManagement: false,
      careProviderWorkplaceConditionsProviderSatisfaction: false,
      careProviderWorkplaceConditionsHealthSafety: false,
      careProviderSkillMixRolePerformance: false,
      careProviderSkillMixRoleExpansionOrExtension: false,
      careProviderSkillMixTaskShiftingSubstitution: false,
      careProviderSkillMixMultidisciplinaryTeams: false,
      careProviderSkillMixVolunteersOrInformalFamilyCaregivers: false,
      careProviderSkillMixCommunicationDistantHealthProfessionals: false,
      careProviderStaffTraining: false,
      careProviderStaffSupport: false,
      careProviderStaffWorkloadWorkflowIntensity: false,
      careProviderStaffContinuityOfCare: false,
      careProviderStaffSelfSharedDecisionMaking: false,
      careProviderSelfManagement: false,

      careSource: false,
      careSourceSiteOfServiceDelivery: false,
      careSourcePhysicalstructureFacilitiesEquipment: false,
      careSourceOrganizationalScale: false,
      careSourceIntegrationOfServices: false,
      careSourceContinuityOfCare: false,
      careSourceOutreach: false,

      careSupport: false,
      careSupportHealthRecordSystems: false,
      careSupportElectronicHealthRecord: false,
      careSupportOtherICTThatSupportIndividuals: false,
      careSupportICTThatSupportIndividualsWhoReceiveCare: false,
      careSupportQualityMonitoringAndImprovementSystems: false,
      careSupportSafetyMonitoringAndImprovementSystems: false,

      implementationStrategies: false,
      implementationConsumerTargetedStrategy: false,
      implementationInformationOrEducationProvision: false,
      implementationBehaviourChangeSupport: false,
      implementationSkillsAndCompetenciesDevelopment: false,
      implementationPersonalSupport: false,
      implementationCommunicationAndDecisionMakingFacilitation: false,
      implementationSystemParticipation: false,

      providerStrategies: false,
      providerStrategyEducationalMaterial: false,
      providerStrategyEducationalMeeting: false,
      providerStrategyEducationalOutreachVisit: false,
      providerStrategyLocalOpinionLeader: false,
      providerStrategyLocalConsensusProcess: false,
      providerStrategyPeerReview: false,
      providerStrategyAuditAndFeedback: false,
      providerStrategyRemindersAndPrompts: false,
      providerStrategyTailoredIntervention: false,
      providerStrategyPatientMediatedIntervention: false,
      providerStrategyMultiFacetedIntervention: false,

      organizationStrategy: false,

      territoryFederalNational: false,
      territoryAlberta: false,
      territoryBritishColumbia: false,
      territoryManitoba: false,
      territoryNewBrunswick: false,
      territoryNewFoundlandAndLabrador: false,
      territoryNorthwestTerritories: false,
      territoryNovaScotia: false,
      territoryNunavut: false,
      territoryOntario: false,
      territoryPrinceEdwardIsland: false,
      territoryQuebec: false,
      territorySaskatchewan: false,
      territoryYukon: false,

      canadianHomeAndCommunityCare: false,
      canadianMentalHealthAndAddictionServices: false,
      canadianIndigenousHealthFederal: false,
      canadianAgingEmergent: false,

      conditions: false,
      conditionInfectiousDiseases: false,
      conditionHIVAIDS: false,
      conditionTuberculosis: false,
      conditionMalaria: false,
      conditionDiarrhoealDisease: false,
      conditionLowerRespiratoryInfections: false,

      conditionNonCommunicableDiseases: false,
      conditionCancer: false,
      conditionCardiovascularDisease: false,
      conditionDiabetes: false,
      conditionAlzheimerAndOtherDementias: false,
      conditionsChronicObstructivePulmonaryDisease: false,

      conditionOther: false,
      conditionMaternalAndChildHealth: false,
      conditionAccidents: false,
      conditionMentalHealthAddictions: false,

      conditionTechnologies: false,
      conditionTechnologyDrugs: false,
      conditionTechnologyDevices: false,
      conditionTechnologyDiagnostics: false,
      conditionTechnologySurgery: false,

      conditionSectors: false,
      conditionSectorPrimaryCare: false,
      conditionSectorSpecialHospitalCare: false,
      conditionSectorRehabilitationCare: false,
      conditionSectorLongTermCare: false,
      conditionSectorPublicHealth: false,

      conditionProviders: false,
      conditionProviderPhysician: false,
      conditionProviderGeneralist: false,
      conditionProviderSpecialist: false,
      conditionProviderNurse: false,
      conditionProviderPharmacist: false,
      conditionProviderAlliedHealthProfessional: false,
      conditionProviderLayCommunityCealthWorker: false,
      conditionProviderInformalFamilyCaregivers: false,

      lmicTargetOfDocument: false,
      lmicAtLeastOneAuthor: false,
      lmicAtLeastOneStudy: false,

      themeOptimalAging: false,
      themeHealthPromotionPrimaryPrevention: false,

      populationChildrenAndYouth: false,
      populationIndigenousPeoples: false,
      populationOldAdults: false,

      evidenceFocusOfDocuments: "",
      evidenceKeyFindings: "",

      ontarioPriorityCommunityBasedCare: false,
      ontarioPriorityHealthSystemPerformanceAndSustainability: false,
      ontarioPriorityHealthyLivingWithAFocusOnTobaccoControl: false,
      ontarioPriorityMentalHealthAndAddictions: false,
      ontarioPriorityNursingResearch: false,
      ontarioPriorityPrimaryCareReform: false,
      ontarioPriorityQualityImprovementAndSafety: false,
      ontarioPrioritySeniorsCare: false,
      ontarioPriorityVulnerableAndSpecialHealthNeedsPopulations: false,
      ontarioPriorityWomensHealth: false,

      healthSystemData: false,
      healthSystemExpenditureReview: false,
      healthSystemNationalAccount: false,
      healthSystemProvincialAccount: false,
      healthSystemResearchPriorities: false,
      healthSystemSituationAnalysis: false,
      healthSystemJurisdictionalReview: false,
      healthSystemPerformanceReview: false,
      healthSystemExternalEvaluation: false,
      healthSystemLiteratureReview: false,
      healthSystemFramework: false,
      healthSystemToolkit: false,
      healthSystemOptionsFraming: false,
      healthSystemGuidance: false,
      healthSystemCitizenPatientInput: false,
      healthSystemStakeholderInput: false,
      healthSystemStakeholderPositionPaper: false,
      healthSystemPoliticalPartyPlatform: false,
      healthSystemGovernmentDiscussionPaper: false,
      healthSystemGovernmentPositionPaper: false,
      healthSystemGovernmentStrategicPlan: false,
      healthSystemGovernmentPolicy: false,
      healthSystemGovernmentLegislation: false,
      healthSystemIntergovernmentalCommunique: false,
      healthSystemIntergovernmentalAccord: false,
      healthSystemGovernmentThirdPartyAccord: false
    }
  }
);

//module.exports = HSEArticle;
module.exports = compose(cleanData, HSEFilter, cleanMongoId);
