const t = require("tcomb");
const Filter = require("./filter");
const { compose } = require("ramda");
const { cleanData, cleanMongoId } = require("../helper");

const SSEFilter = Filter.extend(
  {
    documentType: t.enums.of(
      [
        "Evidence briefs for policy",
        "Overviews of systematic reviews",
        "Systematic reviews of effects",
        "Systematic reviews addressing other questions",
        "Systematic reviews in progress",
        "Systematic reviews being planned",
        "Economic evaluations and costing studies",
        "Health reform descriptions",
        "Health system descriptions",
        "Intergovernmental organizations' health systems documents",
        "Systematic reviews and other types of syntheses",
        "Canada's health systems documents",
        "Ontario's health system documents",
        "NO. After reviewing the document types and eligibility criteria, this record is not eligible for inclusion in HSE."
      ],
      "documentType"
    ),

    // Service System Topics
    programsServices: t.Boolean,
    programsServicesChildren: t.Boolean,
    programsServicesChildrenAdoption: t.Boolean,
    programsServicesChildrenCaregiver: t.Boolean,
    programsServicesChildrenEarlyChildhood: t.Boolean,
    programsServicesChildrenSpecialNeeds: t.Boolean,
    programsServicesChildrenStudentSupport: t.Boolean,
    programsServicesChildrenParentGuardian: t.Boolean,
    programsServicesChildrenChildProtection: t.Boolean,

    citizenship: t.Boolean,
    citizenshipAdmissibility: t.Boolean,
    citizenshipBorder: t.Boolean,
    citizenshipRefugee: t.Boolean,
    citizenshipTemporaryResidence: t.Boolean,
    citizenshipPermanentResidence: t.Boolean,
    citizenshipGrants: t.Boolean,
    citizenshipSettlement: t.Boolean,
    citizenshipVolunteering: t.Boolean,
    citizenshipCulturalIntegration: t.Boolean,
    citizenshipUndocumented: t.Boolean,
    citizenshipMigration: t.Boolean,
    citizenshipDetentionDeportation: t.Boolean,
    citizenshipSubnational: t.Boolean,
    citizenshipInternational: t.Boolean,

    climate: t.Boolean,
    climateEnergy: t.Boolean,
    climateEnergyBuildings: t.Boolean,
    climateEnergyProduction: t.Boolean,
    climateEnergyHouseholds: t.Boolean,
    climateEnergyIndustries: t.Boolean,
    climateEnergyLandUse: t.Boolean,
    climateEnergyTourism: t.Boolean,
    climateEnergyTransport: t.Boolean,

    climateZeroCarbon: t.Boolean,
    climateZeroCarbonNuclear: t.Boolean,
    climateZeroCarbonRenewable: t.Boolean,

    climateElectrification: t.Boolean,
    climateElectrificationAppliances: t.Boolean,
    climateElectrificationSupportingInfra: t.Boolean,
    climateElectrificationVehicles: t.Boolean,

    climateNonEnergy: t.Boolean,
    climateNonEnergyBioSequestration: t.Boolean,
    climateNonEnergyCarbonCapture: t.Boolean,
    climateNonEnergyFugitiveEmissionReduction: t.Boolean,
    climateNonEnergyIndustrialProcessImprovements: t.Boolean,
    climateNonEnergyReuseRecycling: t.Boolean,

    climateChangeRisk: t.Boolean,
    climateChangeRiskFinancial: t.Boolean,
    climateChangeRiskHuman: t.Boolean,
    climateChangeRiskProperty: t.Boolean,
    climateChangeRiskSettlement: t.Boolean,

    community: t.Boolean,
    communityAccessibility: t.Boolean,
    communityDisability: t.Boolean,
    communityGambling: t.Boolean,
    communitySocial: t.Boolean,
    communityServices: t.Boolean,
    communityDevelopment: t.Boolean,
    communityEmergencyResponse: t.Boolean,

    consumer: t.Boolean,
    consumerAwarenessEducation: t.Boolean,
    consumerAdvocacy: t.Boolean,
    consumerAdvertising: t.Boolean,
    consumerPromotion: t.Boolean,
    consumerConsumption: t.Boolean,
    consumerProductSafety: t.Boolean,
    consumerFraud: t.Boolean,
    consumerPrivacy: t.Boolean,
    consumerCompetition: t.Boolean,
    consumerEcommerce: t.Boolean,

    culture: t.Boolean,
    cultureArts: t.Boolean,
    cultureHeritage: t.Boolean,
    cultureIndustries: t.Boolean,
    cultureProtectionism: t.Boolean,
    cultureTraining: t.Boolean,
    cultureMulticulturalism: t.Boolean,
    cultureGenderMainstreaming: t.Boolean,
    cultureGenderEquality: t.Boolean,
    cultureHumanRights: t.Boolean,

    economic: t.Boolean,
    economicAccessToFinance: t.Boolean,
    economicAreaBasedInitiatives: t.Boolean,
    economicBroadbandAccess: t.Boolean,
    economicBusinessAdvice: t.Boolean,
    economicHousingStock: t.Boolean,
    economicHumanCapital: t.Boolean,
    economicInnovation: t.Boolean,
    economicPublicSpace: t.Boolean,
    economicSportCulture: t.Boolean,
    economicTransportationEnhancements: t.Boolean,
    economicFiscalPolicy: t.Boolean,
    economicMonetaryPolicy: t.Boolean,
    economicTradePolicy: t.Boolean,

    education: t.Boolean,
    educationPrePrimary: t.Boolean,
    educationPrimary: t.Boolean,
    educationSecondary: t.Boolean,
    educationTertiary: t.Boolean,
    educationAcademicPlanning: t.Boolean,
    educationRevenueStreams: t.Boolean,
    educationTuitionSubsidy: t.Boolean,
    educationMarketing: t.Boolean,
    educationStreaming: t.Boolean,
    educationCurriculum: t.Boolean,
    educationLiteracyTraining: t.Boolean,
    educationApprenticeships: t.Boolean,
    educationTeaching: t.Boolean,
    educationAssessment: t.Boolean,
    educationStudentEngagement: t.Boolean,
    educationParentEngagement: t.Boolean,
    educationTeacherEngagement: t.Boolean,
    educationCommunityEngagement: t.Boolean,
    educationEmployerEngagement: t.Boolean,

    employment: t.Boolean,
    employmentTraining: t.Boolean,
    employmentWages: t.Boolean,
    employmentBenefits: t.Boolean,
    employmentEmploymentConditions: t.Boolean,
    employmentDisplacedWorkers: t.Boolean,
    employmentUnemployment: t.Boolean,
    employmentUnpaidLabour: t.Boolean,
    employmentWorkplaceSafety: t.Boolean,
    employmentWorkplaceViolence: t.Boolean,
    employmentUnions: t.Boolean,
    employmentLabourMarket: t.Boolean,
    employmentIndustry: t.Boolean,

    energySupply: t.Boolean,
    energySupplyBiofuel: t.Boolean,
    energySupplyBiofuelFirstGeneration: t.Boolean,
    energySupplyBiofuelSecondGeneration: t.Boolean,
    energySupplyCoal: t.Boolean,
    energySupplyHydro: t.Boolean,
    energySupplyHydroPumpedStorage: t.Boolean,
    energySupplyHydroResevoir: t.Boolean,
    energySupplyHydroRunOfRiver: t.Boolean,
    energySupplyHydroTidalRange: t.Boolean,
    energySupplyHydroTidalStream: t.Boolean,
    energySupplyNaturalGas: t.Boolean,
    energySupplyNuclearEnergy: t.Boolean,
    energySupplyPetroleum: t.Boolean,
    energySupplySolarPower: t.Boolean,
    energySupplyWindPower: t.Boolean,
    energySupplyNonCarbon: t.Boolean,
    energySupplyNonCarbonAmonia: t.Boolean,
    energySupplyNonCarbonHydrogen: t.Boolean,
    energySupplyGeothermal: t.Boolean,
    energySupplyGeothermalElectricity: t.Boolean,
    energySupplyGeothermalHeating: t.Boolean,
    energySupplyGeothermalHeatPump: t.Boolean,
    energyWaste: t.Boolean,
    energyWasteBiological: t.Boolean,
    energyWasteThermochemical: t.Boolean,
    energyCoGen: t.Boolean,
    energyCoGenPowerHeat: t.Boolean,
    energyCoGenPowerHeatCooling: t.Boolean,
    energyCoGenPolygeneration: t.Boolean,
    energyStorage: t.Boolean,
    energyStorageDomestic: t.Boolean,
    energyStorageIndustrial: t.Boolean,
    energySystems: t.Boolean,
    energySystemsMix: t.Boolean,
    energySystemsEfficiency: t.Boolean,
    energySystemsGrid: t.Boolean,
    energySystemsGridBalancing: t.Boolean,
    energySystemsSupplySecurity: t.Boolean,

    environmentalConservation: t.Boolean,
    environmentalConservationAir: t.Boolean,
    environmentalConservationLand: t.Boolean,
    environmentalConservationLandPlanning: t.Boolean,
    environmentalConservationLandParks: t.Boolean,
    environmentalConservationWater: t.Boolean,
    environmentalConservationWaterFreshwater: t.Boolean,
    environmentalConservationWaterSeas: t.Boolean,
    environmentalConservationBiodiversity: t.Boolean,
    environmentalConservationBiodiversityFauna: t.Boolean,
    environmentalConservationBiodiversityFlora: t.Boolean,
    environmentalConservationBiodiversityStatusAssessment: t.Boolean,
    environmentalConservationBiodiversitySustainableHarvesting: t.Boolean,

    environmentalConservationRecycling: t.Boolean,
    environmentalConservationRecyclingPersonal: t.Boolean,
    environmentalConservationRecyclingIndustrial: t.Boolean,

    environmentalConservationRestoration: t.Boolean,
    environmentalConservationRestorationRemediation: t.Boolean,
    environmentalConservationRestorationLand: t.Boolean,
    environmentalConservationRestorationRemediation: t.Boolean,

    environmentalConservationWaste: t.Boolean,
    environmentalConservationWasteHazardous: t.Boolean,
    environmentalConservationWasteNonHazardous: t.Boolean,

    environmentalConservationResilience: t.Boolean,
    environmentalConservationResilienceSocial: t.Boolean,
    environmentalConservationResilienceEconomic: t.Boolean,
    environmentalConservationResilienceInstitutional: t.Boolean,
    environmentalConservationResiliencePhysical: t.Boolean,
    environmentalConservationResilienceNatural: t.Boolean,

    environmentalConservationThreats: t.Boolean,
    environmentalConservationThreatsFires: t.Boolean,
    environmentalConservationThreatsInvasiveSpecies: t.Boolean,
    environmentalConservationThreatsLight: t.Boolean,
    environmentalConservationThreatsNoise: t.Boolean,

    financial: t.Boolean,
    financialSocialAssistance: t.Boolean,
    financialMinimumWage: t.Boolean,
    financialWageDisparity: t.Boolean,
    financialEmploymentInsurance: t.Boolean,
    financialPensionsAllowances: t.Boolean,
    financialPovertyReduction: t.Boolean,
    financialGoodServices: t.Boolean,
    financialGuaranteedIncome: t.Boolean,
    financialIncomeRedistribution: t.Boolean,
    financialAssetReporting: t.Boolean,

    foodSafety: t.Boolean,
    foodSafetyAccess: t.Boolean,
    foodSafetyNutritionalAwareness: t.Boolean,
    foodSafetyAid: t.Boolean,
    foodSafetyStandards: t.Boolean,
    foodSafetyImportExport: t.Boolean,
    foodSafetyInternationalRelief: t.Boolean,

    government: t.Boolean,
    governmentIdLicensingRegistration: t.Boolean,
    governmentServiceAwareness: t.Boolean,
    governmentEgovernment: t.Boolean,
    governmentServiceCoordination: t.Boolean,
    governmentCorruptionProtection: t.Boolean,
    governmentInclusivityProtection: t.Boolean,
    governmentAccountabilityProtection: t.Boolean,
    governmentElectionAdministration: t.Boolean,

    housing: t.Boolean,
    housingAccess: t.Boolean,
    housingTemporary: t.Boolean,
    housingSocial: t.Boolean,
    housingAffordable: t.Boolean,
    housingAssistance: t.Boolean,
    housingMix: t.Boolean,
    housingSafety: t.Boolean,
    housingPropertyRights: t.Boolean,

    infrastructure: t.Boolean,
    infrastructureCapitalPlanning: t.Boolean,
    infrastructureUrbanPlanning: t.Boolean,
    infrastructureSocial: t.Boolean,
    infrastructureBroadband: t.Boolean,
    infrastructureTransportation: t.Boolean,
    infrastructureWasteManagement: t.Boolean,
    infrastructureWaterSanitation: t.Boolean,
    infrastructureSustainableDevelopment: t.Boolean,
    infrastructureCapitalSpending: t.Boolean,
    infrastructurePublicFinancing: t.Boolean,
    infrastructurePublicPrivatePartnerships: t.Boolean,
    infrastructurePrivateFinancing: t.Boolean,
    infrastructureForeignInvestment: t.Boolean,
    infrastructureRiskManagement: t.Boolean,

    naturalResources: t.Boolean,
    naturalResourcesAquatic: t.Boolean,
    naturalResourcesAquaticFisheries: t.Boolean,
    naturalResourcesAquaticPlants: t.Boolean,
    naturalResourcesWater: t.Boolean,
    naturalResourcesForests: t.Boolean,
    naturalResourcesForestsTimber: t.Boolean,
    naturalResourcesGround: t.Boolean,
    naturalResourcesGroundMetals: t.Boolean,
    naturalResourcesGroundMinerals: t.Boolean,
    naturalResourcesGroundPetroleum: t.Boolean,
    naturalResourcesGroundGas: t.Boolean,
    naturalResourcesWildlife: t.Boolean,

    publicSafety: t.Boolean,
    publicSafetyCrimePrevention: t.Boolean,
    publicSafetyCrimeReduction: t.Boolean,
    publicSafetySecurityServices: t.Boolean,
    publicSafetyNationalSecurity: t.Boolean,
    publicSafetyCounterTerrorism: t.Boolean,
    publicSafetyMilitary: t.Boolean,
    publicSafetyPolicing: t.Boolean,
    publicSafetyCourtSystem: t.Boolean,
    publicSafetyRestorativeJustice: t.Boolean,
    publicSafetyYouthJustice: t.Boolean,
    publicSafetyDomesticViolence: t.Boolean,
    publicSafetyVictimSupport: t.Boolean,
    publicSafetyOffenderDiversion: t.Boolean,
    publicSafetySentencing: t.Boolean,
    publicSafetyPrisonAdministration: t.Boolean,
    publicSafetyProbationParole: t.Boolean,
    publicSafetyCommunityCorrections: t.Boolean,
    publicSafetyReintegration: t.Boolean,

    recreation: t.Boolean,
    recreationPromotion: t.Boolean,
    recreationPublicSpaces: t.Boolean,
    recreationCommunityRecreation: t.Boolean,
    recreationPrivateRecreation: t.Boolean,
    recreationCompetitiveSport: t.Boolean,

    transportation: t.Boolean,
    transportationAccessibleOptions: t.Boolean,
    transportationCongestionManagement: t.Boolean,
    transportationPublic: t.Boolean,
    transportationPedestrianSafety: t.Boolean,
    transportationCyclingSafety: t.Boolean,
    transportationSafety: t.Boolean,
    transportationSustainableOptions: t.Boolean,
    transportationSubsidies: t.Boolean,
    transportationRoadTolls: t.Boolean,

    system: t.Boolean,
    systemGovernance: t.Boolean,
    systemGovernancePolicy: t.Boolean,
    systemGovernancePolicyCentralization: t.Boolean,
    systemGovernancePolicyAccountability: t.Boolean,
    systemGovernancePolicyStewardship: t.Boolean,
    systemGovernancePolicyDecisionMaking: t.Boolean,
    systemGovernancePolicyCorruptionProtections: t.Boolean,
    systemGovernancePolicy: t.Boolean,
    systemOrganizational: t.Boolean,
    systemOrganizationalOwnership: t.Boolean,
    systemOrganizationalManagement: t.Boolean,
    systemOrganizationalAccreditation: t.Boolean,
    systemOrganizationalNetworks: t.Boolean,
    systemCommercial: t.Boolean,
    systemCommercialLicensure: t.Boolean,
    systemCommercialPatentsProfits: t.Boolean,
    systemCommercialPricingPurchasing: t.Boolean,
    systemCommercialMarketing: t.Boolean,
    systemCommercialSales: t.Boolean,
    systemCommercialLiability: t.Boolean,
    systemProfessional: t.Boolean,
    systemProfessionalTrainingLicensure: t.Boolean,
    systemProfessionalScopePractice: t.Boolean,
    systemProfessionalSettingPractice: t.Boolean,
    systemProfessionalContinuingCompetence: t.Boolean,
    systemProfessionalQualitySafety: t.Boolean,
    systemProfessionalLiability: t.Boolean,
    systemProfessionalStrikeJobAction: t.Boolean,
    systemCitizen: t.Boolean,
    systemCitizenPolicy: t.Boolean,
    systemCitizenSystemMonitoring: t.Boolean,
    systemCitizenServiceDelivery: t.Boolean,
    systemCitizenComplaintsManagement: t.Boolean,
    systemCitizenStakeholderPolicy: t.Boolean,

    financial: t.Boolean,
    financingSystems: t.Boolean,
    financialTaxation: t.Boolean,
    financialSocialHealthInsurance: t.Boolean,
    financialCommunityBasedHealthInsurance: t.Boolean,
    financialCommunityLoanFunds: t.Boolean,
    financialPrivateInsurance: t.Boolean,
    financialHealthSavingsAccountsIndividuallyFinanced: t.Boolean,
    financialUserFees: t.Boolean,
    financialDonorContributions: t.Boolean,
    financialFundraising: t.Boolean,

    fundingOrganization: t.Boolean,
    fundingOrganizationServiceFees: t.Boolean,
    fundingOrganizationCapitation: t.Boolean,
    fundingOrganizationGlobalBudget: t.Boolean,
    fundingOrganizationCaseMixFunding: t.Boolean,
    fundingOrganizationPaymentsPenalties: t.Boolean,

    remuneratingProvider: t.Boolean,
    remuneratingProviderServiceFees: t.Boolean,
    remuneratingProviderCapitation: t.Boolean,
    remuneratingProviderSalary: t.Boolean,
    remuneratingProviderEpisodePayment: t.Boolean,
    remuneratingProviderFundholding: t.Boolean,
    remuneratingProviderPaymentPenalties: t.Boolean,

    purchasing: t.Boolean,
    purchasingScope: t.Boolean,
    purchasingCoveredReimbursedOrganizations: t.Boolean,
    purchasingRestrictions: t.Boolean,
    purchasingCaps: t.Boolean,
    purchasingApprovalRequirements: t.Boolean,
    purchasingSubstitutes: t.Boolean,

    incentivizingCitizen: t.Boolean,
    incentivizingCitizenPremium: t.Boolean,
    incentivizingCitizenCostSharing: t.Boolean,
    incentivizingCitizenSavingsThirdPartyContributions: t.Boolean,
    incentivizingCitizenSavingsTargetedPaymentsPenalties: t.Boolean,

    deliveryArrangement: t.Boolean,
    deliveryArrangementDesign: t.Boolean,
    deliveryArrangementDesignAvailability: t.Boolean,
    deliveryArrangementDesignTimelyAcess: t.Boolean,
    deliveryArrangementDesignCulturallyAppropriate: t.Boolean,
    deliveryArrangementDesignCaseManagement: t.Boolean,
    deliveryArrangementDesignDiseaseManagement: t.Boolean,
    deliveryArrangementDesignGroup: t.Boolean,

    serviceProvider: t.Boolean,
    serviceProviderAvailability: t.Boolean,
    serviceProviderRecruitmentRetention: t.Boolean,
    serviceProviderPerformanceManagement: t.Boolean,
    serviceProviderWorkplaceConditionsProviderSatisfaction: t.Boolean,
    serviceProviderWorkplaceConditionsHealthSafety: t.Boolean,
    serviceProviderSkillMixRolePerformance: t.Boolean,
    serviceProviderSkillMixRoleExpansionOrExtension: t.Boolean,
    serviceProviderSkillMixTaskShiftingSubstitution: t.Boolean,
    serviceProviderSkillMixMultidisciplinaryTeams: t.Boolean,
    serviceProviderSkillMixVolunteersOrInformalFamilyCaregivers: t.Boolean,
    serviceProviderSkillMixCommunicationDistantHealthProfessionals: t.Boolean,
    serviceProviderStaffTraining: t.Boolean,
    serviceProviderStaffSupport: t.Boolean,
    serviceProviderStaffWorkloadWorkflowIntensity: t.Boolean,
    serviceProviderStaffContinuityOfCare: t.Boolean,
    serviceProviderStaffSelfSharedDecisionMaking: t.Boolean,
    serviceProviderSelfManagement: t.Boolean,

    serviceLocation: t.Boolean,
    serviceLocationSite: t.Boolean,
    serviceLocationPhysicalStructure: t.Boolean,
    serviceLocationOrganizationalScale: t.Boolean,
    serviceLocationOrganizationalStructure: t.Boolean,
    serviceLocationServiceIntegration: t.Boolean,
    serviceLocationServiceContinuity: t.Boolean,
    serviceLocationOutreach: t.Boolean,

    serviceSupport: t.Boolean,
    serviceSupportHealthRecordSystems: t.Boolean,
    serviceSupportElectronicHealthRecord: t.Boolean,
    serviceSupportOtherICTThatSupportIndividuals: t.Boolean,
    serviceSupportICTThatSupportIndividualsWhoReceiveCare: t.Boolean,
    serviceSupportQualityMonitoringAndImprovementSystems: t.Boolean,
    serviceSupportSafetyMonitoringAndImprovementSystems: t.Boolean,

    implementationStrategies: t.Boolean,
    implementationCitizenTargeted: t.Boolean,
    implementationCitizenTargetedInformationOrEducationProvision: t.Boolean,
    implementationCitizenTargetedBehaviourChangeSupport: t.Boolean,
    implementationCitizenTargetedSkillsAndCompetenciesDevelopment: t.Boolean,
    implementationCitizenTargetedPersonalSupport: t.Boolean,
    implementationCitizenTargetedCommunicationAndDecisionMakingFacilitation:
      t.Boolean,
    implementationCitizenTargetedSystemParticipation: t.Boolean,

    implementationProviderTargeted: t.Boolean,
    implementationProviderTargetedEducationalMaterial: t.Boolean,
    implementationProviderTargetedEducationalMeeting: t.Boolean,
    implementationProviderTargetedEducationalOutreachVisit: t.Boolean,
    implementationProviderTargetedLocalOpinionLeader: t.Boolean,
    implementationProviderTargetedLocalConsensusProcess: t.Boolean,
    implementationProviderTargetedPeerReview: t.Boolean,
    implementationProviderTargetedRemindersAndPrompts: t.Boolean,
    implementationProviderTargetedTailoredIntervention: t.Boolean,
    implementationProviderTargetedCitizenMediatedIntervention: t.Boolean,
    implementationProviderTargetedMultiFacetedIntervention: t.Boolean,

    implementationOrganizationTargeted: t.Boolean,

    sustainableDevelopmentGoals: t.Boolean,
    sustainableDevelopmentGoalsNoPoverty: t.Boolean,
    sustainableDevelopmentGoalsZeroHunger: t.Boolean,
    sustainableDevelopmentGoalsGoodHealth: t.Boolean,
    sustainableDevelopmentGoalsQualityEducation: t.Boolean,
    sustainableDevelopmentGoalsGenderEquality: t.Boolean,
    sustainableDevelopmentGoalsCleanWater: t.Boolean,
    sustainableDevelopmentGoalsAffordableCleanEnergy: t.Boolean,
    sustainableDevelopmentGoalsDecentWorkEconomicGrowth: t.Boolean,
    sustainableDevelopmentGoalsIndustryInnovationInfrastructure: t.Boolean,
    sustainableDevelopmentGoalsReducedInequalities: t.Boolean,
    sustainableDevelopmentGoalsSustainableCitiesCommunities: t.Boolean,
    sustainableDevelopmentGoalsResponsibleConsumptionProduction: t.Boolean,
    sustainableDevelopmentGoalsClimateAction: t.Boolean,
    sustainableDevelopmentGoalsLifeBelowWater: t.Boolean,
    sustainableDevelopmentGoalsLifeOnLand: t.Boolean,
    sustainableDevelopmentGoalsPeaceJusticeStrongInstitutions: t.Boolean,
    sustainableDevelopmentGoalsPartnerships: t.Boolean,

    perspectives: t.Boolean,
    perspectivesPopulations: t.Boolean,
    perspectivesPopulationChildrenYouth: t.Boolean,
    perspectivesPopulationEthnoculturalMinorities: t.Boolean,
    perspectivesPopulationLinguisticMinorities: t.Boolean,
    perspectivesPopulationImigrantsRefugees: t.Boolean,
    perspectivesPopulationIndigenousPeoples: t.Boolean,
    perspectivesPopulationHomeless: t.Boolean,
    perspectivesPopulationLGBTQ: t.Boolean,
    perspectivesPopulationOlderAdults: t.Boolean,
    perspectivesPopulationRuralRemote: t.Boolean,
    perspectivesPopulationDisabilities: t.Boolean,

    perspectivesProvider: t.Boolean,
    perspectivesProviderEconomic: t.Boolean,
    perspectivesProviderEducation: t.Boolean,
    perspectivesProviderEmployment: t.Boolean,
    perspectivesProviderHealth: t.Boolean,
    perspectivesProviderHousing: t.Boolean,
    perspectivesProviderPeerReview: t.Boolean,
    perspectivesProviderSocialInclusion: t.Boolean,
    perspectivesProviderWellBeing: t.Boolean,
    perspectivesProviderCitizenIntervention: t.Boolean,
    perspectivesProvider: t.Boolean,

    perspectivesDisciplines: t.Boolean,
    perspectivesDisciplineAnthropology: t.Boolean,
    perspectivesDisciplineArts: t.Boolean,
    perspectivesDisciplineBusinessAdministration: t.Boolean,
    perspectivesDisciplineCommunication: t.Boolean,
    perspectivesDisciplineCriminology: t.Boolean,
    perspectivesDisciplineEconomics: t.Boolean,
    perspectivesDisciplineEngineering: t.Boolean,
    perspectivesDisciplineGeography: t.Boolean,
    perspectivesDisciplineGerontology: t.Boolean,
    perspectivesDisciplineHistory: t.Boolean,
    perspectivesDisciplineLaw: t.Boolean,
    perspectivesDisciplinePhilosophy: t.Boolean,
    perspectivesDisciplinePoliticalScience: t.Boolean,
    perspectivesDisciplinePsychology: t.Boolean,
    perspectivesDisciplinePublicAdministration: t.Boolean,
    perspectivesDisciplineSocialWork: t.Boolean,
    perspectivesDisciplineSociology: t.Boolean
  },
  {
    defaultProps: {
      type: "sse",
      documentType:
        "NO. After reviewing the document types and eligibility criteria, this record is not eligible for inclusion in SSE."
    }
  }
);

//module.exports = HSEArticle;
module.exports = compose(cleanData, SSEFilter, cleanMongoId);
