const t = require("tcomb");
const Filter = require("./filter");
const { compose } = require("ramda");
const { cleanData, cleanMongoId } = require("../helper");

const SSEFilter = Filter.extend(
  {
    documentType: t.String,

    // Service System Topics
    programsServices: t.Boolean,
    programsServicesChildren: t.Boolean,
    programsServicesChildrenAdoption: t.Boolean,
    programsServicesChildrenCaregiver: t.Boolean,
    programsServicesChildrenEarlyChildhood: t.Boolean,
    programsServicesChildrenSpecialNeeds: t.Boolean,
    programsServicesChildrenStudentSupport: t.Boolean,
    programsServicesChildrenParentGuardian: t.Boolean,
    programsServicesChildrenChildProtection: t.Boolean,

    citizenship: t.Boolean,
    citizenshipAdmissibility: t.Boolean,
    citizenshipBorder: t.Boolean,
    citizenshipRefugee: t.Boolean,
    citizenshipTemporaryResidence: t.Boolean,
    citizenshipPermanentResidence: t.Boolean,
    citizenshipGrants: t.Boolean,
    citizenshipSettlement: t.Boolean,
    citizenshipVolunteering: t.Boolean,
    citizenshipCulturalIntegration: t.Boolean,
    citizenshipUndocumented: t.Boolean,
    citizenshipMigration: t.Boolean,
    citizenshipDetentionDeportation: t.Boolean,
    citizenshipSubnational: t.Boolean,
    citizenshipInternational: t.Boolean,

    climate: t.Boolean,
    climateEnergy: t.Boolean,
    climateEnergyBuildings: t.Boolean,
    climateEnergyProduction: t.Boolean,
    climateEnergyHouseholds: t.Boolean,
    climateEnergyIndustries: t.Boolean,
    climateEnergyLandUse: t.Boolean,
    climateEnergyTourism: t.Boolean,
    climateEnergyTransport: t.Boolean,

    climateZeroCarbon: t.Boolean,
    climateZeroCarbonNuclear: t.Boolean,
    climateZeroCarbonRenewable: t.Boolean,

    climateElectrification: t.Boolean,
    climateElectrificationAppliances: t.Boolean,
    climateElectrificationSupportingInfra: t.Boolean,
    climateElectrificationVehicles: t.Boolean,

    climateNonEnergy: t.Boolean,
    climateNonEnergyBioSequestration: t.Boolean,
    climateNonEnergyCarbonCapture: t.Boolean,
    climateNonEnergyFugitiveEmissionReduction: t.Boolean,
    climateNonEnergyIndustrialProcessImprovements: t.Boolean,
    climateNonEnergyReuseRecycling: t.Boolean,

    climateChangeRisk: t.Boolean,
    climateChangeRiskFinancial: t.Boolean,
    climateChangeRiskHuman: t.Boolean,
    climateChangeRiskProperty: t.Boolean,
    climateChangeRiskSettlement: t.Boolean,

    community: t.Boolean,
    communityAccessibility: t.Boolean,
    communityDisability: t.Boolean,
    communityGambling: t.Boolean,
    communitySocial: t.Boolean,
    communityServices: t.Boolean,
    communityDevelopment: t.Boolean,
    communityEmergencyResponse: t.Boolean,

    consumer: t.Boolean,
    consumerAwarenessEducation: t.Boolean,
    consumerAdvocacy: t.Boolean,
    consumerAdvertising: t.Boolean,
    consumerPromotion: t.Boolean,
    consumerConsumption: t.Boolean,
    consumerProductSafety: t.Boolean,
    consumerFraud: t.Boolean,
    consumerPrivacy: t.Boolean,
    consumerCompetition: t.Boolean,
    consumerEcommerce: t.Boolean,

    culture: t.Boolean,
    cultureArts: t.Boolean,
    cultureHeritage: t.Boolean,
    cultureIndustries: t.Boolean,
    cultureProtectionism: t.Boolean,
    cultureTraining: t.Boolean,
    cultureMulticulturalism: t.Boolean,
    cultureGenderMainstreaming: t.Boolean,
    cultureGenderEquality: t.Boolean,
    cultureHumanRights: t.Boolean,

    economic: t.Boolean,
    economicAccessToFinance: t.Boolean,
    economicAreaBasedInitiatives: t.Boolean,
    economicBroadbandAccess: t.Boolean,
    economicBusinessAdvice: t.Boolean,
    economicHousingStock: t.Boolean,
    economicHumanCapital: t.Boolean,
    economicInnovation: t.Boolean,
    economicPublicSpace: t.Boolean,
    economicSportCulture: t.Boolean,
    economicTransportationEnhancements: t.Boolean,
    economicFiscalPolicy: t.Boolean,
    economicMonetaryPolicy: t.Boolean,
    economicTradePolicy: t.Boolean,

    education: t.Boolean,
    educationPrePrimary: t.Boolean,
    educationPrimary: t.Boolean,
    educationSecondary: t.Boolean,
    educationTertiary: t.Boolean,
    educationAcademicPlanning: t.Boolean,
    educationRevenueStreams: t.Boolean,
    educationTuitionSubsidy: t.Boolean,
    educationMarketing: t.Boolean,
    educationStreaming: t.Boolean,
    educationCurriculum: t.Boolean,
    educationLiteracyTraining: t.Boolean,
    educationApprenticeships: t.Boolean,
    educationTeaching: t.Boolean,
    educationAssessment: t.Boolean,
    educationStudentEngagement: t.Boolean,
    educationParentEngagement: t.Boolean,
    educationTeacherEngagement: t.Boolean,
    educationCommunityEngagement: t.Boolean,
    educationEmployerEngagement: t.Boolean,

    employment: t.Boolean,
    employmentTraining: t.Boolean,
    employmentWages: t.Boolean,
    employmentBenefits: t.Boolean,
    employmentEmploymentConditions: t.Boolean,
    employmentDisplacedWorkers: t.Boolean,
    employmentUnemployment: t.Boolean,
    employmentUnpaidLabour: t.Boolean,
    employmentWorkplaceSafety: t.Boolean,
    employmentWorkplaceViolence: t.Boolean,
    employmentUnions: t.Boolean,
    employmentLabourMarket: t.Boolean,
    employmentIndustry: t.Boolean,

    energySupply: t.Boolean,
    energySupplyBiofuel: t.Boolean,
    energySupplyBiofuelFirstGeneration: t.Boolean,
    energySupplyBiofuelSecondGeneration: t.Boolean,
    energySupplyCoal: t.Boolean,
    energySupplyHydro: t.Boolean,
    energySupplyHydroPumpedStorage: t.Boolean,
    energySupplyHydroResevoir: t.Boolean,
    energySupplyHydroRunOfRiver: t.Boolean,
    energySupplyHydroTidalRange: t.Boolean,
    energySupplyHydroTidalStream: t.Boolean,
    energySupplyNaturalGas: t.Boolean,
    energySupplyNuclearEnergy: t.Boolean,
    energySupplyPetroleum: t.Boolean,
    energySupplySolarPower: t.Boolean,
    energySupplyWindPower: t.Boolean,
    energySupplyNonCarbon: t.Boolean,
    energySupplyNonCarbonAmonia: t.Boolean,
    energySupplyNonCarbonHydrogen: t.Boolean,
    energySupplyGeothermal: t.Boolean,
    energySupplyGeothermalElectricity: t.Boolean,
    energySupplyGeothermalHeating: t.Boolean,
    energySupplyGeothermalHeatPump: t.Boolean,
    energyWaste: t.Boolean,
    energyWasteBiological: t.Boolean,
    energyWasteThermochemical: t.Boolean,
    energyCoGen: t.Boolean,
    energyCoGenPowerHeat: t.Boolean,
    energyCoGenPowerHeatCooling: t.Boolean,
    energyCoGenPolygeneration: t.Boolean,
    energyStorage: t.Boolean,
    energyStorageDomestic: t.Boolean,
    energyStorageIndustrial: t.Boolean,
    energySystems: t.Boolean,
    energySystemsMix: t.Boolean,
    energySystemsEfficiency: t.Boolean,
    energySystemsGrid: t.Boolean,
    energySystemsGridBalancing: t.Boolean,
    energySystemsSupplySecurity: t.Boolean,

    environmentalConservation: t.Boolean,
    environmentalConservationAir: t.Boolean,
    environmentalConservationLand: t.Boolean,
    environmentalConservationLandPlanning: t.Boolean,
    environmentalConservationLandParks: t.Boolean,
    environmentalConservationWater: t.Boolean,
    environmentalConservationWaterFreshwater: t.Boolean,
    environmentalConservationWaterSeas: t.Boolean,
    environmentalConservationBiodiversity: t.Boolean,
    environmentalConservationBiodiversityFauna: t.Boolean,
    environmentalConservationBiodiversityFlora: t.Boolean,
    environmentalConservationBiodiversityStatusAssessment: t.Boolean,
    environmentalConservationBiodiversitySustainableHarvesting: t.Boolean,

    environmentalConservationRecycling: t.Boolean,
    environmentalConservationRecyclingPersonal: t.Boolean,
    environmentalConservationRecyclingIndustrial: t.Boolean,

    environmentalConservationRestoration: t.Boolean,
    environmentalConservationRestorationRemediation: t.Boolean,
    environmentalConservationRestorationLand: t.Boolean,
    environmentalConservationRehabilitationLand: t.Boolean,

    environmentalConservationWaste: t.Boolean,
    environmentalConservationWasteHazardous: t.Boolean,
    environmentalConservationWasteNonHazardous: t.Boolean,

    environmentalConservationResilience: t.Boolean,
    environmentalConservationResilienceSocial: t.Boolean,
    environmentalConservationResilienceEconomic: t.Boolean,
    environmentalConservationResilienceInstitutional: t.Boolean,
    environmentalConservationResiliencePhysical: t.Boolean,
    environmentalConservationResilienceNatural: t.Boolean,

    environmentalConservationThreats: t.Boolean,
    environmentalConservationThreatsFires: t.Boolean,
    environmentalConservationThreatsInvasiveSpecies: t.Boolean,
    environmentalConservationThreatsLight: t.Boolean,
    environmentalConservationThreatsNoise: t.Boolean,

    financial: t.Boolean,
    financialSocialAssistance: t.Boolean,
    financialMinimumWage: t.Boolean,
    financialWageDisparity: t.Boolean,
    financialEmploymentInsurance: t.Boolean,
    financialPensionsAllowances: t.Boolean,
    financialPovertyReduction: t.Boolean,
    financialGoodServices: t.Boolean,
    financialGuaranteedIncome: t.Boolean,
    financialIncomeRedistribution: t.Boolean,
    financialIncomeReporting: t.Boolean,
    financialAssetReporting: t.Boolean,

    foodSafety: t.Boolean,
    foodSafetyAccess: t.Boolean,
    foodSafetyNutritionalAwareness: t.Boolean,
    foodSafetyAid: t.Boolean,
    foodSafetyStandards: t.Boolean,
    foodSafetyImportExport: t.Boolean,
    foodSafetyInternationalRelief: t.Boolean,

    government: t.Boolean,
    governmentIdLicensingRegistration: t.Boolean,
    governmentServiceAwareness: t.Boolean,
    governmentEgovernment: t.Boolean,
    governmentServiceCoordination: t.Boolean,
    governmentCorruptionProtection: t.Boolean,
    governmentInclusivityProtection: t.Boolean,
    governmentAccountabilityProtection: t.Boolean,
    governmentElectionAdministration: t.Boolean,

    housing: t.Boolean,
    housingAccess: t.Boolean,
    housingTemporary: t.Boolean,
    housingSocial: t.Boolean,
    housingAffordable: t.Boolean,
    housingAssistance: t.Boolean,
    housingMix: t.Boolean,
    housingSafety: t.Boolean,
    housingPropertyRights: t.Boolean,

    infrastructure: t.Boolean,
    infrastructureCapitalPlanning: t.Boolean,
    infrastructureUrbanPlanning: t.Boolean,
    infrastructureSocial: t.Boolean,
    infrastructureBroadband: t.Boolean,
    infrastructureTransportation: t.Boolean,
    infrastructureWasteManagement: t.Boolean,
    infrastructureWaterSanitation: t.Boolean,
    infrastructureSustainableDevelopment: t.Boolean,
    infrastructureCapitalSpending: t.Boolean,
    infrastructurePublicFinancing: t.Boolean,
    infrastructurePublicPrivatePartnerships: t.Boolean,
    infrastructurePrivateFinancing: t.Boolean,
    infrastructureForeignInvestment: t.Boolean,
    infrastructureRiskManagement: t.Boolean,

    naturalResources: t.Boolean,
    naturalResourcesAquatic: t.Boolean,
    naturalResourcesAquaticFisheries: t.Boolean,
    naturalResourcesAquaticPlants: t.Boolean,
    naturalResourcesWater: t.Boolean,
    naturalResourcesForests: t.Boolean,
    naturalResourcesForestsTimber: t.Boolean,
    naturalResourcesGround: t.Boolean,
    naturalResourcesGroundMetals: t.Boolean,
    naturalResourcesGroundMinerals: t.Boolean,
    naturalResourcesGroundPetroleum: t.Boolean,
    naturalResourcesGroundGas: t.Boolean,
    naturalResourcesWildlife: t.Boolean,

    publicSafety: t.Boolean,
    publicSafetyCrimePrevention: t.Boolean,
    publicSafetyCrimeReduction: t.Boolean,
    publicSafetySecurityServices: t.Boolean,
    publicSafetyNationalSecurity: t.Boolean,
    publicSafetyCounterTerrorism: t.Boolean,
    publicSafetyMilitary: t.Boolean,
    publicSafetyPolicing: t.Boolean,
    publicSafetyCourtSystem: t.Boolean,
    publicSafetyRestorativeJustice: t.Boolean,
    publicSafetyYouthJustice: t.Boolean,
    publicSafetyDomesticViolence: t.Boolean,
    publicSafetyVictimSupport: t.Boolean,
    publicSafetyOffenderDiversion: t.Boolean,
    publicSafetySentencing: t.Boolean,
    publicSafetyPrisonAdministration: t.Boolean,
    publicSafetyProbationParole: t.Boolean,
    publicSafetyCommunityCorrections: t.Boolean,
    publicSafetyReintegration: t.Boolean,

    recreation: t.Boolean,
    recreationPromotion: t.Boolean,
    recreationPublicSpaces: t.Boolean,
    recreationCommunityRecreation: t.Boolean,
    recreationPrivateRecreation: t.Boolean,
    recreationCompetitiveSport: t.Boolean,

    transportation: t.Boolean,
    transportationAccessibleOptions: t.Boolean,
    transportationCongestionManagement: t.Boolean,
    transportationPublic: t.Boolean,
    transportationPedestrianSafety: t.Boolean,
    transportationCyclingSafety: t.Boolean,
    transportationSafety: t.Boolean,
    transportationSustainableOptions: t.Boolean,
    transportationSubsidies: t.Boolean,
    transportationRoadTolls: t.Boolean,

    system: t.Boolean,
    systemGovernance: t.Boolean,
    systemGovernancePolicy: t.Boolean,
    systemGovernancePolicyCentralization: t.Boolean,
    systemGovernancePolicyAccountability: t.Boolean,
    systemGovernancePolicyStewardship: t.Boolean,
    systemGovernancePolicyDecisionMaking: t.Boolean,
    systemGovernancePolicyCorruptionProtections: t.Boolean,
    systemOrganizational: t.Boolean,
    systemOrganizationalOwnership: t.Boolean,
    systemOrganizationalManagement: t.Boolean,
    systemOrganizationalAccreditation: t.Boolean,
    systemOrganizationalNetworks: t.Boolean,
    systemCommercial: t.Boolean,
    systemCommercialLicensure: t.Boolean,
    systemCommercialPatentsProfits: t.Boolean,
    systemCommercialPricingPurchasing: t.Boolean,
    systemCommercialMarketing: t.Boolean,
    systemCommercialSales: t.Boolean,
    systemCommercialLiability: t.Boolean,
    systemProfessional: t.Boolean,
    systemProfessionalTrainingLicensure: t.Boolean,
    systemProfessionalScopePractice: t.Boolean,
    systemProfessionalSettingPractice: t.Boolean,
    systemProfessionalContinuingCompetence: t.Boolean,
    systemProfessionalQualitySafety: t.Boolean,
    systemProfessionalLiability: t.Boolean,
    systemProfessionalStrikeJobAction: t.Boolean,
    systemCitizen: t.Boolean,
    systemCitizenPolicy: t.Boolean,
    systemCitizenSystemMonitoring: t.Boolean,
    systemCitizenServiceDelivery: t.Boolean,
    systemCitizenComplaintsManagement: t.Boolean,
    systemCitizenStakeholderPolicy: t.Boolean,

    financial: t.Boolean,
    financingSystems: t.Boolean,
    financialTaxation: t.Boolean,
    financialSocialHealthInsurance: t.Boolean,
    financialCommunityBasedHealthInsurance: t.Boolean,
    financialCommunityLoanFunds: t.Boolean,
    financialPrivateInsurance: t.Boolean,
    financialHealthSavingsAccountsIndividuallyFinanced: t.Boolean,
    financialUserFees: t.Boolean,
    financialDonorContributions: t.Boolean,
    financialFundraising: t.Boolean,

    fundingOrganization: t.Boolean,
    fundingOrganizationServiceFees: t.Boolean,
    fundingOrganizationCapitation: t.Boolean,
    fundingOrganizationGlobalBudget: t.Boolean,
    fundingOrganizationCaseMixFunding: t.Boolean,
    fundingOrganizationPaymentsPenalties: t.Boolean,

    remuneratingProvider: t.Boolean,
    remuneratingProviderServiceFees: t.Boolean,
    remuneratingProviderCapitation: t.Boolean,
    remuneratingProviderSalary: t.Boolean,
    remuneratingProviderEpisodePayment: t.Boolean,
    remuneratingProviderFundholding: t.Boolean,
    remuneratingProviderPaymentPenalties: t.Boolean,

    purchasing: t.Boolean,
    purchasingScope: t.Boolean,
    purchasingCoveredReimbursedOrganizations: t.Boolean,
    purchasingRestrictions: t.Boolean,
    purchasingCaps: t.Boolean,
    purchasingApprovalRequirements: t.Boolean,
    purchasingSubstitutes: t.Boolean,

    incentivizingCitizen: t.Boolean,
    incentivizingCitizenPremium: t.Boolean,
    incentivizingCitizenCostSharing: t.Boolean,
    incentivizingCitizenSavingsThirdPartyContributions: t.Boolean,
    incentivizingCitizenSavingsTargetedPaymentsPenalties: t.Boolean,

    deliveryArrangement: t.Boolean,
    deliveryArrangementDesign: t.Boolean,
    deliveryArrangementDesignAvailability: t.Boolean,
    deliveryArrangementDesignTimelyAcess: t.Boolean,
    deliveryArrangementDesignCulturallyAppropriate: t.Boolean,
    deliveryArrangementDesignCaseManagement: t.Boolean,
    deliveryArrangementDesignServicesPackage: t.Boolean,
    deliveryArrangementDesignGroup: t.Boolean,

    serviceProvider: t.Boolean,
    serviceProviderAvailability: t.Boolean,
    serviceProviderRecruitmentRetention: t.Boolean,
    serviceProviderPerformanceManagement: t.Boolean,
    serviceProviderWorkplaceConditionsProviderSatisfaction: t.Boolean,
    serviceProviderWorkplaceConditionsHealthSafety: t.Boolean,
    serviceProviderSkillMixRolePerformance: t.Boolean,
    serviceProviderSkillMixRoleExpansionOrExtension: t.Boolean,
    serviceProviderSkillMixTaskShiftingSubstitution: t.Boolean,
    serviceProviderSkillMixMultidisciplinaryTeams: t.Boolean,
    serviceProviderSkillMixVolunteersOrInformalFamilyCaregivers: t.Boolean,
    serviceProviderSkillMixCommunicationDistantHealthProfessionals: t.Boolean,
    serviceProviderStaffTraining: t.Boolean,
    serviceProviderStaffSupport: t.Boolean,
    serviceProviderStaffWorkloadWorkflowIntensity: t.Boolean,
    serviceProviderStaffContinuityOfCare: t.Boolean,
    serviceProviderStaffSelfSharedDecisionMaking: t.Boolean,
    serviceProviderSelfManagement: t.Boolean,

    serviceLocation: t.Boolean,
    serviceLocationSite: t.Boolean,
    serviceLocationPhysicalStructure: t.Boolean,
    serviceLocationOrganizationalScale: t.Boolean,
    serviceLocationOrganizationalStructure: t.Boolean,
    serviceLocationServiceIntegration: t.Boolean,
    serviceLocationServiceContinuity: t.Boolean,
    serviceLocationOutreach: t.Boolean,

    serviceSupport: t.Boolean,
    serviceSupportHealthRecordSystems: t.Boolean,
    serviceSupportElectronicHealthRecord: t.Boolean,
    serviceSupportOtherICTThatSupportIndividuals: t.Boolean,
    serviceSupportICTThatSupportIndividualsWhoReceiveCare: t.Boolean,
    serviceSupportFinancialMonitoring: t.Boolean,
    serviceSupportQualityMonitoringAndImprovementSystems: t.Boolean,
    serviceSupportSafetyMonitoringAndImprovementSystems: t.Boolean,

    implementationStrategies: t.Boolean,
    implementationCitizenTargeted: t.Boolean,
    implementationCitizenTargetedInformationOrEducationProvision: t.Boolean,
    implementationCitizenTargetedBehaviourChangeSupport: t.Boolean,
    implementationCitizenTargetedSkillsAndCompetenciesDevelopment: t.Boolean,
    implementationCitizenTargetedPersonalSupport: t.Boolean,
    implementationCitizenTargetedCommunicationAndDecisionMakingFacilitation:
      t.Boolean,
    implementationCitizenTargetedSystemParticipation: t.Boolean,

    implementationProviderTargeted: t.Boolean,
    implementationProviderTargetedEducationalMaterial: t.Boolean,
    implementationProviderTargetedEducationalMeeting: t.Boolean,
    implementationProviderTargetedEducationalOutreachVisit: t.Boolean,
    implementationProviderTargetedLocalOpinionLeader: t.Boolean,
    implementationProviderTargetedLocalConsensusProcess: t.Boolean,
    implementationProviderTargetedPeerReview: t.Boolean,
    implementationProviderTargetedRemindersAndPrompts: t.Boolean,
    implementationProviderTargetedTailoredIntervention: t.Boolean,
    implementationProviderTargetedCitizenMediatedIntervention: t.Boolean,
    implementationProviderTargetedMultiFacetedIntervention: t.Boolean,

    implementationOrganizationTargeted: t.Boolean,

    sustainableDevelopmentGoals: t.Boolean,
    sustainableDevelopmentGoalsNoPoverty: t.Boolean,
    sustainableDevelopmentGoalsZeroHunger: t.Boolean,
    sustainableDevelopmentGoalsGoodHealth: t.Boolean,
    sustainableDevelopmentGoalsQualityEducation: t.Boolean,
    sustainableDevelopmentGoalsGenderEquality: t.Boolean,
    sustainableDevelopmentGoalsCleanWater: t.Boolean,
    sustainableDevelopmentGoalsAffordableCleanEnergy: t.Boolean,
    sustainableDevelopmentGoalsDecentWorkEconomicGrowth: t.Boolean,
    sustainableDevelopmentGoalsIndustryInnovationInfrastructure: t.Boolean,
    sustainableDevelopmentGoalsReducedInequalities: t.Boolean,
    sustainableDevelopmentGoalsSustainableCitiesCommunities: t.Boolean,
    sustainableDevelopmentGoalsResponsibleConsumptionProduction: t.Boolean,
    sustainableDevelopmentGoalsClimateAction: t.Boolean,
    sustainableDevelopmentGoalsLifeBelowWater: t.Boolean,
    sustainableDevelopmentGoalsLifeOnLand: t.Boolean,
    sustainableDevelopmentGoalsPeaceJusticeStrongInstitutions: t.Boolean,
    sustainableDevelopmentGoalsPartnerships: t.Boolean,

    perspectives: t.Boolean,
    perspectivesPopulations: t.Boolean,
    perspectivesPopulationChildrenYouth: t.Boolean,
    perspectivesPopulationEthnoculturalMinorities: t.Boolean,
    perspectivesPopulationLinguisticMinorities: t.Boolean,
    perspectivesPopulationImigrantsRefugees: t.Boolean,
    perspectivesPopulationIndigenousPeoples: t.Boolean,
    perspectivesPopulationHomeless: t.Boolean,
    perspectivesPopulationLGBTQ: t.Boolean,
    perspectivesPopulationOlderAdults: t.Boolean,
    perspectivesPopulationRuralRemote: t.Boolean,
    perspectivesPopulationDisabilities: t.Boolean,

    perspectivesProvider: t.Boolean,
    perspectivesProviderEconomic: t.Boolean,
    perspectivesProviderEducation: t.Boolean,
    perspectivesProviderEmployment: t.Boolean,
    perspectivesProviderHealth: t.Boolean,
    perspectivesProviderHousing: t.Boolean,
    perspectivesProviderPeerReview: t.Boolean,
    perspectivesProviderSocialInclusion: t.Boolean,
    perspectivesProviderWellBeing: t.Boolean,
    perspectivesProviderCitizenIntervention: t.Boolean,
    perspectivesProviderOther: t.Boolean,

    perspectivesDisciplines: t.Boolean,
    perspectivesDisciplineAnthropology: t.Boolean,
    perspectivesDisciplineArts: t.Boolean,
    perspectivesDisciplineBusinessAdministration: t.Boolean,
    perspectivesDisciplineCommunication: t.Boolean,
    perspectivesDisciplineCriminology: t.Boolean,
    perspectivesDisciplineEconomics: t.Boolean,
    perspectivesDisciplineEngineering: t.Boolean,
    perspectivesDisciplineGeography: t.Boolean,
    perspectivesDisciplineGerontology: t.Boolean,
    perspectivesDisciplineHistory: t.Boolean,
    perspectivesDisciplineLaw: t.Boolean,
    perspectivesDisciplinePhilosophy: t.Boolean,
    perspectivesDisciplinePoliticalScience: t.Boolean,
    perspectivesDisciplinePsychology: t.Boolean,
    perspectivesDisciplinePublicAdministration: t.Boolean,
    perspectivesDisciplineSocialWork: t.Boolean,
    perspectivesDisciplineSociology: t.Boolean,

    // LMIC Focus
    lmicTargetOfDocument: t.Boolean,
    lmicAtLeastOneAuthor: t.Boolean,
    lmicAtLeastOneStudy: t.Boolean,

    // Theme
    themeOptimalAging: t.Boolean,

    ageNeonates: t.Boolean,
    agePediatrics: t.Boolean,
    ageAdolescents: t.Boolean,
    ageAdults: t.Boolean,
    ageGeriatrics: t.Boolean,

    targetIndividual: t.Boolean,
    targetFamily: t.Boolean,
    targetCommunity: t.Boolean,
    targetSystem: t.Boolean
  },
  {
    defaultProps: {
      type: "sse",
      documentType:
        "NO. After reviewing the document types and eligibility criteria, this record is not eligible for inclusion in SSE.",

      programsServices: false,
      programsServicesChildren: false,
      programsServicesChildrenAdoption: false,
      programsServicesChildrenCaregiver: false,
      programsServicesChildrenEarlyChildhood: false,
      programsServicesChildrenSpecialNeeds: false,
      programsServicesChildrenStudentSupport: false,
      programsServicesChildrenParentGuardian: false,
      programsServicesChildrenChildProtection: false,

      citizenship: false,
      citizenshipAdmissibility: false,
      citizenshipBorder: false,
      citizenshipRefugee: false,
      citizenshipTemporaryResidence: false,
      citizenshipPermanentResidence: false,
      citizenshipGrants: false,
      citizenshipSettlement: false,
      citizenshipVolunteering: false,
      citizenshipCulturalIntegration: false,
      citizenshipUndocumented: false,
      citizenshipMigration: false,
      citizenshipDetentionDeportation: false,
      citizenshipSubnational: false,
      citizenshipInternational: false,

      climate: false,
      climateEnergy: false,
      climateEnergyBuildings: false,
      climateEnergyProduction: false,
      climateEnergyHouseholds: false,
      climateEnergyIndustries: false,
      climateEnergyLandUse: false,
      climateEnergyTourism: false,
      climateEnergyTransport: false,

      climateZeroCarbon: false,
      climateZeroCarbonNuclear: false,
      climateZeroCarbonRenewable: false,

      climateElectrification: false,
      climateElectrificationAppliances: false,
      climateElectrificationSupportingInfra: false,
      climateElectrificationVehicles: false,

      climateNonEnergy: false,
      climateNonEnergyBioSequestration: false,
      climateNonEnergyCarbonCapture: false,
      climateNonEnergyFugitiveEmissionReduction: false,
      climateNonEnergyIndustrialProcessImprovements: false,
      climateNonEnergyReuseRecycling: false,

      climateChangeRisk: false,
      climateChangeRiskFinancial: false,
      climateChangeRiskHuman: false,
      climateChangeRiskProperty: false,
      climateChangeRiskSettlement: false,

      community: false,
      communityAccessibility: false,
      communityDisability: false,
      communityGambling: false,
      communitySocial: false,
      communityServices: false,
      communityDevelopment: false,
      communityEmergencyResponse: false,

      consumer: false,
      consumerAwarenessEducation: false,
      consumerAdvocacy: false,
      consumerAdvertising: false,
      consumerPromotion: false,
      consumerConsumption: false,
      consumerProductSafety: false,
      consumerFraud: false,
      consumerPrivacy: false,
      consumerCompetition: false,
      consumerEcommerce: false,

      culture: false,
      cultureArts: false,
      cultureHeritage: false,
      cultureIndustries: false,
      cultureProtectionism: false,
      cultureTraining: false,
      cultureMulticulturalism: false,
      cultureGenderMainstreaming: false,
      cultureGenderEquality: false,
      cultureHumanRights: false,

      economic: false,
      economicAccessToFinance: false,
      economicAreaBasedInitiatives: false,
      economicBroadbandAccess: false,
      economicBusinessAdvice: false,
      economicHousingStock: false,
      economicHumanCapital: false,
      economicInnovation: false,
      economicPublicSpace: false,
      economicSportCulture: false,
      economicTransportationEnhancements: false,
      economicFiscalPolicy: false,
      economicMonetaryPolicy: false,
      economicTradePolicy: false,

      education: false,
      educationPrePrimary: false,
      educationPrimary: false,
      educationSecondary: false,
      educationTertiary: false,
      educationAcademicPlanning: false,
      educationRevenueStreams: false,
      educationTuitionSubsidy: false,
      educationMarketing: false,
      educationStreaming: false,
      educationCurriculum: false,
      educationLiteracyTraining: false,
      educationApprenticeships: false,
      educationTeaching: false,
      educationAssessment: false,
      educationStudentEngagement: false,
      educationParentEngagement: false,
      educationTeacherEngagement: false,
      educationCommunityEngagement: false,
      educationEmployerEngagement: false,

      employment: false,
      employmentTraining: false,
      employmentWages: false,
      employmentBenefits: false,
      employmentEmploymentConditions: false,
      employmentDisplacedWorkers: false,
      employmentUnemployment: false,
      employmentUnpaidLabour: false,
      employmentWorkplaceSafety: false,
      employmentWorkplaceViolence: false,
      employmentUnions: false,
      employmentLabourMarket: false,
      employmentIndustry: false,

      energySupply: false,
      energySupplyBiofuel: false,
      energySupplyBiofuelFirstGeneration: false,
      energySupplyBiofuelSecondGeneration: false,
      energySupplyCoal: false,
      energySupplyHydro: false,
      energySupplyHydroPumpedStorage: false,
      energySupplyHydroResevoir: false,
      energySupplyHydroRunOfRiver: false,
      energySupplyHydroTidalRange: false,
      energySupplyHydroTidalStream: false,
      energySupplyNaturalGas: false,
      energySupplyNuclearEnergy: false,
      energySupplyPetroleum: false,
      energySupplySolarPower: false,
      energySupplyWindPower: false,
      energySupplyNonCarbon: false,
      energySupplyNonCarbonAmonia: false,
      energySupplyNonCarbonHydrogen: false,
      energySupplyGeothermal: false,
      energySupplyGeothermalElectricity: false,
      energySupplyGeothermalHeating: false,
      energySupplyGeothermalHeatPump: false,
      energyWaste: false,
      energyWasteBiological: false,
      energyWasteThermochemical: false,
      energyCoGen: false,
      energyCoGenPowerHeat: false,
      energyCoGenPowerHeatCooling: false,
      energyCoGenPolygeneration: false,
      energyStorage: false,
      energyStorageDomestic: false,
      energyStorageIndustrial: false,
      energySystems: false,
      energySystemsMix: false,
      energySystemsEfficiency: false,
      energySystemsGrid: false,
      energySystemsGridBalancing: false,
      energySystemsSupplySecurity: false,

      environmentalConservation: false,
      environmentalConservationAir: false,
      environmentalConservationLand: false,
      environmentalConservationLandPlanning: false,
      environmentalConservationLandParks: false,
      environmentalConservationWater: false,
      environmentalConservationWaterFreshwater: false,
      environmentalConservationWaterSeas: false,
      environmentalConservationBiodiversity: false,
      environmentalConservationBiodiversityFauna: false,
      environmentalConservationBiodiversityFlora: false,
      environmentalConservationBiodiversityStatusAssessment: false,
      environmentalConservationBiodiversitySustainableHarvesting: false,

      environmentalConservationRecycling: false,
      environmentalConservationRecyclingPersonal: false,
      environmentalConservationRecyclingIndustrial: false,

      environmentalConservationRestoration: false,
      environmentalConservationRestorationRemediation: false,
      environmentalConservationRestorationLand: false,
      environmentalConservationRehabilitationLand: false,

      environmentalConservationWaste: false,
      environmentalConservationWasteHazardous: false,
      environmentalConservationWasteNonHazardous: false,

      environmentalConservationResilience: false,
      environmentalConservationResilienceSocial: false,
      environmentalConservationResilienceEconomic: false,
      environmentalConservationResilienceInstitutional: false,
      environmentalConservationResiliencePhysical: false,
      environmentalConservationResilienceNatural: false,

      environmentalConservationThreats: false,
      environmentalConservationThreatsFires: false,
      environmentalConservationThreatsInvasiveSpecies: false,
      environmentalConservationThreatsLight: false,
      environmentalConservationThreatsNoise: false,

      financial: false,
      financialSocialAssistance: false,
      financialMinimumWage: false,
      financialWageDisparity: false,
      financialEmploymentInsurance: false,
      financialPensionsAllowances: false,
      financialPovertyReduction: false,
      financialGoodServices: false,
      financialGuaranteedIncome: false,
      financialIncomeRedistribution: false,
      financialIncomeReporting: false,
      financialAssetReporting: false,

      foodSafety: false,
      foodSafetyAccess: false,
      foodSafetyNutritionalAwareness: false,
      foodSafetyAid: false,
      foodSafetyStandards: false,
      foodSafetyImportExport: false,
      foodSafetyInternationalRelief: false,

      government: false,
      governmentIdLicensingRegistration: false,
      governmentServiceAwareness: false,
      governmentEgovernment: false,
      governmentServiceCoordination: false,
      governmentCorruptionProtection: false,
      governmentInclusivityProtection: false,
      governmentAccountabilityProtection: false,
      governmentElectionAdministration: false,

      housing: false,
      housingAccess: false,
      housingTemporary: false,
      housingSocial: false,
      housingAffordable: false,
      housingAssistance: false,
      housingMix: false,
      housingSafety: false,
      housingPropertyRights: false,

      infrastructure: false,
      infrastructureCapitalPlanning: false,
      infrastructureUrbanPlanning: false,
      infrastructureSocial: false,
      infrastructureBroadband: false,
      infrastructureTransportation: false,
      infrastructureWasteManagement: false,
      infrastructureWaterSanitation: false,
      infrastructureSustainableDevelopment: false,
      infrastructureCapitalSpending: false,
      infrastructurePublicFinancing: false,
      infrastructurePublicPrivatePartnerships: false,
      infrastructurePrivateFinancing: false,
      infrastructureForeignInvestment: false,
      infrastructureRiskManagement: false,

      naturalResources: false,
      naturalResourcesAquatic: false,
      naturalResourcesAquaticFisheries: false,
      naturalResourcesAquaticPlants: false,
      naturalResourcesWater: false,
      naturalResourcesForests: false,
      naturalResourcesForestsTimber: false,
      naturalResourcesGround: false,
      naturalResourcesGroundMetals: false,
      naturalResourcesGroundMinerals: false,
      naturalResourcesGroundPetroleum: false,
      naturalResourcesGroundGas: false,
      naturalResourcesWildlife: false,

      publicSafety: false,
      publicSafetyCrimePrevention: false,
      publicSafetyCrimeReduction: false,
      publicSafetySecurityServices: false,
      publicSafetyNationalSecurity: false,
      publicSafetyCounterTerrorism: false,
      publicSafetyMilitary: false,
      publicSafetyPolicing: false,
      publicSafetyCourtSystem: false,
      publicSafetyRestorativeJustice: false,
      publicSafetyYouthJustice: false,
      publicSafetyDomesticViolence: false,
      publicSafetyVictimSupport: false,
      publicSafetyOffenderDiversion: false,
      publicSafetySentencing: false,
      publicSafetyPrisonAdministration: false,
      publicSafetyProbationParole: false,
      publicSafetyCommunityCorrections: false,
      publicSafetyReintegration: false,

      recreation: false,
      recreationPromotion: false,
      recreationPublicSpaces: false,
      recreationCommunityRecreation: false,
      recreationPrivateRecreation: false,
      recreationCompetitiveSport: false,

      transportation: false,
      transportationAccessibleOptions: false,
      transportationCongestionManagement: false,
      transportationPublic: false,
      transportationPedestrianSafety: false,
      transportationCyclingSafety: false,
      transportationSafety: false,
      transportationSustainableOptions: false,
      transportationSubsidies: false,
      transportationRoadTolls: false,

      system: false,
      systemGovernance: false,
      systemGovernancePolicy: false,
      systemGovernancePolicyCentralization: false,
      systemGovernancePolicyAccountability: false,
      systemGovernancePolicyStewardship: false,
      systemGovernancePolicyDecisionMaking: false,
      systemGovernancePolicyCorruptionProtections: false,
      systemOrganizational: false,
      systemOrganizationalOwnership: false,
      systemOrganizationalManagement: false,
      systemOrganizationalAccreditation: false,
      systemOrganizationalNetworks: false,
      systemCommercial: false,
      systemCommercialLicensure: false,
      systemCommercialPatentsProfits: false,
      systemCommercialPricingPurchasing: false,
      systemCommercialMarketing: false,
      systemCommercialSales: false,
      systemCommercialLiability: false,
      systemProfessional: false,
      systemProfessionalTrainingLicensure: false,
      systemProfessionalScopePractice: false,
      systemProfessionalSettingPractice: false,
      systemProfessionalContinuingCompetence: false,
      systemProfessionalQualitySafety: false,
      systemProfessionalLiability: false,
      systemProfessionalStrikeJobAction: false,
      systemCitizen: false,
      systemCitizenPolicy: false,
      systemCitizenSystemMonitoring: false,
      systemCitizenServiceDelivery: false,
      systemCitizenComplaintsManagement: false,
      systemCitizenStakeholderPolicy: false,

      financial: false,
      financingSystems: false,
      financialTaxation: false,
      financialSocialHealthInsurance: false,
      financialCommunityBasedHealthInsurance: false,
      financialCommunityLoanFunds: false,
      financialPrivateInsurance: false,
      financialHealthSavingsAccountsIndividuallyFinanced: false,
      financialUserFees: false,
      financialDonorContributions: false,
      financialFundraising: false,

      fundingOrganization: false,
      fundingOrganizationServiceFees: false,
      fundingOrganizationCapitation: false,
      fundingOrganizationGlobalBudget: false,
      fundingOrganizationCaseMixFunding: false,
      fundingOrganizationPaymentsPenalties: false,

      remuneratingProvider: false,
      remuneratingProviderServiceFees: false,
      remuneratingProviderCapitation: false,
      remuneratingProviderSalary: false,
      remuneratingProviderEpisodePayment: false,
      remuneratingProviderFundholding: false,
      remuneratingProviderPaymentPenalties: false,

      purchasing: false,
      purchasingScope: false,
      purchasingCoveredReimbursedOrganizations: false,
      purchasingRestrictions: false,
      purchasingCaps: false,
      purchasingApprovalRequirements: false,
      purchasingSubstitutes: false,

      incentivizingCitizen: false,
      incentivizingCitizenPremium: false,
      incentivizingCitizenCostSharing: false,
      incentivizingCitizenSavingsThirdPartyContributions: false,
      incentivizingCitizenSavingsTargetedPaymentsPenalties: false,

      deliveryArrangement: false,
      deliveryArrangementDesign: false,
      deliveryArrangementDesignAvailability: false,
      deliveryArrangementDesignTimelyAcess: false,
      deliveryArrangementDesignCulturallyAppropriate: false,
      deliveryArrangementDesignCaseManagement: false,
      deliveryArrangementDesignServicesPackage: false,
      deliveryArrangementDesignGroup: false,

      serviceProvider: false,
      serviceProviderAvailability: false,
      serviceProviderRecruitmentRetention: false,
      serviceProviderPerformanceManagement: false,
      serviceProviderWorkplaceConditionsProviderSatisfaction: false,
      serviceProviderWorkplaceConditionsHealthSafety: false,
      serviceProviderSkillMixRolePerformance: false,
      serviceProviderSkillMixRoleExpansionOrExtension: false,
      serviceProviderSkillMixTaskShiftingSubstitution: false,
      serviceProviderSkillMixMultidisciplinaryTeams: false,
      serviceProviderSkillMixVolunteersOrInformalFamilyCaregivers: false,
      serviceProviderSkillMixCommunicationDistantHealthProfessionals: false,
      serviceProviderStaffTraining: false,
      serviceProviderStaffSupport: false,
      serviceProviderStaffWorkloadWorkflowIntensity: false,
      serviceProviderStaffContinuityOfCare: false,
      serviceProviderStaffSelfSharedDecisionMaking: false,
      serviceProviderSelfManagement: false,

      serviceLocation: false,
      serviceLocationSite: false,
      serviceLocationPhysicalStructure: false,
      serviceLocationOrganizationalScale: false,
      serviceLocationOrganizationalStructure: false,
      serviceLocationServiceIntegration: false,
      serviceLocationServiceContinuity: false,
      serviceLocationOutreach: false,

      serviceSupport: false,
      serviceSupportHealthRecordSystems: false,
      serviceSupportElectronicHealthRecord: false,
      serviceSupportOtherICTThatSupportIndividuals: false,
      serviceSupportICTThatSupportIndividualsWhoReceiveCare: false,
      serviceSupportFinancialMonitoring: false,
      serviceSupportQualityMonitoringAndImprovementSystems: false,
      serviceSupportSafetyMonitoringAndImprovementSystems: false,

      implementationStrategies: false,
      implementationCitizenTargeted: false,
      implementationCitizenTargetedInformationOrEducationProvision: false,
      implementationCitizenTargetedBehaviourChangeSupport: false,
      implementationCitizenTargetedSkillsAndCompetenciesDevelopment: false,
      implementationCitizenTargetedPersonalSupport: false,
      implementationCitizenTargetedCommunicationAndDecisionMakingFacilitation: false,
      implementationCitizenTargetedSystemParticipation: false,

      implementationProviderTargeted: false,
      implementationProviderTargetedEducationalMaterial: false,
      implementationProviderTargetedEducationalMeeting: false,
      implementationProviderTargetedEducationalOutreachVisit: false,
      implementationProviderTargetedLocalOpinionLeader: false,
      implementationProviderTargetedLocalConsensusProcess: false,
      implementationProviderTargetedPeerReview: false,
      implementationProviderTargetedRemindersAndPrompts: false,
      implementationProviderTargetedTailoredIntervention: false,
      implementationProviderTargetedCitizenMediatedIntervention: false,
      implementationProviderTargetedMultiFacetedIntervention: false,

      implementationOrganizationTargeted: false,

      sustainableDevelopmentGoals: false,
      sustainableDevelopmentGoalsNoPoverty: false,
      sustainableDevelopmentGoalsZeroHunger: false,
      sustainableDevelopmentGoalsGoodHealth: false,
      sustainableDevelopmentGoalsQualityEducation: false,
      sustainableDevelopmentGoalsGenderEquality: false,
      sustainableDevelopmentGoalsCleanWater: false,
      sustainableDevelopmentGoalsAffordableCleanEnergy: false,
      sustainableDevelopmentGoalsDecentWorkEconomicGrowth: false,
      sustainableDevelopmentGoalsIndustryInnovationInfrastructure: false,
      sustainableDevelopmentGoalsReducedInequalities: false,
      sustainableDevelopmentGoalsSustainableCitiesCommunities: false,
      sustainableDevelopmentGoalsResponsibleConsumptionProduction: false,
      sustainableDevelopmentGoalsClimateAction: false,
      sustainableDevelopmentGoalsLifeBelowWater: false,
      sustainableDevelopmentGoalsLifeOnLand: false,
      sustainableDevelopmentGoalsPeaceJusticeStrongInstitutions: false,
      sustainableDevelopmentGoalsPartnerships: false,

      perspectives: false,
      perspectivesPopulations: false,
      perspectivesPopulationChildrenYouth: false,
      perspectivesPopulationEthnoculturalMinorities: false,
      perspectivesPopulationLinguisticMinorities: false,
      perspectivesPopulationImigrantsRefugees: false,
      perspectivesPopulationIndigenousPeoples: false,
      perspectivesPopulationHomeless: false,
      perspectivesPopulationLGBTQ: false,
      perspectivesPopulationOlderAdults: false,
      perspectivesPopulationRuralRemote: false,
      perspectivesPopulationDisabilities: false,

      perspectivesProvider: false,
      perspectivesProviderEconomic: false,
      perspectivesProviderEducation: false,
      perspectivesProviderEmployment: false,
      perspectivesProviderHealth: false,
      perspectivesProviderHousing: false,
      perspectivesProviderPeerReview: false,
      perspectivesProviderSocialInclusion: false,
      perspectivesProviderWellBeing: false,
      perspectivesProviderCitizenIntervention: false,
      perspectivesProviderOther: false,

      perspectivesDisciplines: false,
      perspectivesDisciplineAnthropology: false,
      perspectivesDisciplineArts: false,
      perspectivesDisciplineBusinessAdministration: false,
      perspectivesDisciplineCommunication: false,
      perspectivesDisciplineCriminology: false,
      perspectivesDisciplineEconomics: false,
      perspectivesDisciplineEngineering: false,
      perspectivesDisciplineGeography: false,
      perspectivesDisciplineGerontology: false,
      perspectivesDisciplineHistory: false,
      perspectivesDisciplineLaw: false,
      perspectivesDisciplinePhilosophy: false,
      perspectivesDisciplinePoliticalScience: false,
      perspectivesDisciplinePsychology: false,
      perspectivesDisciplinePublicAdministration: false,
      perspectivesDisciplineSocialWork: false,
      perspectivesDisciplineSociology: false,

      lmicTargetOfDocument: false,
      lmicAtLeastOneAuthor: false,
      lmicAtLeastOneStudy: false,

      themeOptimalAging: false,

      ageNeonates: false,
      agePediatrics: false,
      ageAdolescents: false,
      ageAdults: false,
      ageGeriatrics: false,

      targetIndividual: false,
      targetFamily: false,
      targetCommunity: false,
      targetSystem: false
    }
  }
);

//module.exports = HSEArticle;
module.exports = compose(cleanData, SSEFilter, cleanMongoId);
